CREATE TABLE IF NOT EXISTS re_balance_proforma (
  id INT AUTO_INCREMENT PRIMARY KEY,
  balance_number INT NOT NULL,
  balance_proforma_number VARCHAR(50) NOT NULL,
  source_proforma_id INT NOT NULL,
  client_id INT NOT NULL,
  is_gst TINYINT(1) DEFAULT 0,
  pricing_snapshot LONGTEXT,
  ads_snapshot LONGTEXT,
  discount_snapshot TEXT,
  notes_snapshot LONGTEXT,
  terms_snapshot LONGTEXT,
  remarks_snapshot TEXT,
  client_instructions_snapshot TEXT,
  duration_start_date DATE,
  duration_end_date DATE,
  show_google_ad TINYINT(1) DEFAULT 1,
  show_meta_ad TINYINT(1) DEFAULT 1,
  total_amount DECIMAL(12,2) DEFAULT 0.00,
  received_amount DECIMAL(12,2) DEFAULT 0.00,
  current_balance DECIMAL(12,2) DEFAULT 0.00,
  created_by VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_source_proforma (source_proforma_id),
  INDEX idx_client (client_id),
  INDEX idx_balance_number (balance_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
